# Generated by Django 5.0.1 on 2024-01-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('p', 'published'), ('d', 'draft')], max_length=1),
        ),
    ]
